services:
  - type: web
    name: oveloai-assistant
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python app/rag_system_faiss.py
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OLLAMA_HOST
        value: http://127.0.0.1:11434
      - key: OLLAMA_MODEL
        value: phi3:mini
      - key: FAISS_DB_PATH
        value: faiss_db
      - key: SMTP_SERVER
        value: # YOUR_SMTP_SERVER
      - key: SMTP_PORT
        value: # YOUR_SMTP_PORT
      - key: SMTP_USERNAME
        value: # YOUR_SMTP_USERNAME
      - key: SMTP_PASSWORD
        value: # YOUR_SMTP_PASSWORD
      - key: RECEIVER_EMAIL
        value: # YOUR_RECEIVER_EMAIL
